#+TITLE: 저를 소개합니다.
#+LAYOUT: post
#+jekyll_tags: here!
#+jekyll_categories: Lifestyle
#+DATE: 2024-10-13


안녕하세요!

저는, 인하대학교, 부산대학교 에서 수학을 전공하였고, AI 분야에서 전문성을 가지고 있습니다. 최근 3년 8개월 동안 버즈니에서 Research Engineer로 근무하며 전문연구요원 복무를 완료하였구요. 현재는 DataScientist, Research Engineer 직군으로 구직활동을 하고 있습니다. 아래는 저에대한 소개 글과 강점 어필이 있고 마지막으로 resume를 첨부하였습니다. 감사합니다. (__) 

** Who I Am

안녕하세요. AI전반 그리고 데이터를 처리하는 일 자체에 강점을 갖고 지속적으로 성장중인 남성욱 이라고 합니다. 수학을 전공하였으며 대학원 과정 중 산업수학센터에서 ml기반의 많은 문제들을 접하고 해결해 왔습니다. 버즈니에서 리서치 엔지니어로써 다양한 업무들을 수행해 왔고, 새롭게 문제를 정의하는 일 그리고 데이터를 끈기있게 바라보고 의미를 이끌어내는 일에 강점이 있다고 말씀드리고 싶습니다. 기술적으로는 ElasticSearch,  airflow, k8s, git action, argoCD, kafka, fastapi 등과 같은 기술 스택을 다룰 수 있습니다. 또한, 대시보드에 관하여 redash나 grafana를 활용하며, 데이터베이스 관리 및 스토리지로는 mongoDB, postgresDB, S3 Storage 등을 익숙하게 다룰 수 있습니다. deep learning framework로는 pytorch를 일반 ml에 대해서는 scikit-learn을 사용하고, 데이터 처리에 관하여는 pandas, polars, seaborn등을 활용합니다. 연구적으로는 nlp, vision 양쪽 도메인을 모두 관심을 두고 연구하고 있고, 최근에는 개인 블로그를 운영하며 개발전반, AI전반을 두루 정리해나가고 있습니다.

제 삶에 있어서 뚜렷하게 세운 목표는 "40살 이내에 은퇴하자" 입니다. 이 글을 쓰는 시점을 기준으로 앞으로 8년이 남았고 어떤 의미에서 보면 터무니 없고 현실성 없어 보일 수 도 있겠습니다만, 저는 너무도 진심이고 조금 더 젊은 때에 경제적인 자유를 이루고 주어진 짧은 시간을 더 알차게 더 많은 것들을 경험해보며 보내고 싶습니다. 이런 이유로 앞으로 3~5년 내에는 직장내에서의 최대한의 성취가 제 인생에 있어 가장 먼저 달성 해내야 할 마일스톤이라는 점 이야기 드리고 싶습니다.    

 <hr>

** Resume
아래는 한장으로 정리한 이력서 입니다. 2024년 11월 6일 기준 비젼을 공유하며 함께 일할 수 있는 직장을 찾고 있습니다. DataScientist, Research Engineer 직군을 희망 합니다. 관련해서 문의사항등의 연락은 000namc@gmail.com 으로 부탁드리겠습니다. 가벼운 커피챗도 좋습니다! 감사합니다.  
https://000namc.xyz/nginx/blog/resume.pdf
